name: chorus-detection
channels:
  - conda-forge
  - defaults
dependencies:
  - audioread=3.0.1=py38haa244fe_1
  - brotli=1.1.0=hcfcfb64_1
  - brotli-bin=1.1.0=hcfcfb64_1
  - brotli-python=1.1.0=py38hd3f51b4_1
  - bzip2=1.0.8=hcfcfb64_5
  - ca-certificates=2024.2.2=h56e8100_0
  - certifi=2024.2.2=pyhd8ed1ab_0
  - cffi=1.16.0=py38h91455d4_0
  - charset-normalizer=3.3.2=pyhd8ed1ab_0
  - contourpy=1.1.1=py38hb1fd069_1
  - cycler=0.12.1=pyhd8ed1ab_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - fonttools=4.51.0=py38h91455d4_0
  - freetype=2.12.1=hdaf720e_2
  - importlib-metadata=7.1.0=pyha770c72_0
  - importlib-resources=6.4.0=pyhd8ed1ab_0
  - importlib_resources=6.4.0=pyhd8ed1ab_0
  - intel-openmp=2024.1.0=h57928b3_965
  - joblib=1.4.0=pyhd8ed1ab_0
  - kiwisolver=1.4.5=py38hb1fd069_1
  - lame=3.100=hcfcfb64_1003
  - lazy_loader=0.4=pyhd8ed1ab_0
  - lcms2=2.16=h67d730c_0
  - lerc=4.0.0=h63175ca_0
  - libblas=3.9.0=22_win64_mkl
  - libbrotlicommon=1.1.0=hcfcfb64_1
  - libbrotlidec=1.1.0=hcfcfb64_1
  - libbrotlienc=1.1.0=hcfcfb64_1
  - libcblas=3.9.0=22_win64_mkl
  - libdeflate=1.20=hcfcfb64_0
  - libffi=3.4.2=h8ffe710_5
  - libflac=1.4.3=h63175ca_0
  - libhwloc=2.10.0=default_h2fffb23_1000
  - libiconv=1.17=hcfcfb64_2
  - libjpeg-turbo=3.0.0=hcfcfb64_1
  - liblapack=3.9.0=22_win64_mkl
  - libogg=1.3.4=h8ffe710_1
  - libopus=1.3.1=h8ffe710_1
  - libpng=1.6.43=h19919ed_0
  - librosa=0.10.1=pyhd8ed1ab_0
  - libsndfile=1.2.2=h81429f1_1
  - libsqlite=3.45.2=hcfcfb64_0
  - libtiff=4.6.0=hddb2be6_3
  - libvorbis=1.3.7=h0e60522_0
  - libwebp-base=1.3.2=hcfcfb64_1
  - libxcb=1.15=hcd874cb_0
  - libxml2=2.12.6=hc3477c8_1
  - libzlib=1.2.13=hcfcfb64_5
  - llvmlite=0.41.1=py38h19421c1_0
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - matplotlib-base=3.7.3=py38h2724991_0
  - mkl=2024.1.0=h66d3029_692
  - mpg123=1.32.6=h63175ca_0
  - msgpack-python=1.0.7=py38hb1fd069_0
  - msys2-conda-epoch=20160418=1
  - munkres=1.1.4=pyh9f0ad1d_0
  - numba=0.58.1=py38h4a59444_0
  - openjpeg=2.5.2=h3d672ee_0
  - openssl=3.2.1=hcfcfb64_1
  - packaging=24.0=pyhd8ed1ab_0
  - pandas=2.0.3=py38hf08cf0d_1
  - pillow=10.3.0=py38h894f861_0
  - pip=24.0=pyhd8ed1ab_0
  - platformdirs=4.2.0=pyhd8ed1ab_0
  - pooch=1.8.1=pyhd8ed1ab_0
  - pthread-stubs=0.4=hcd874cb_1001
  - pthreads-win32=2.9.1=hfa6e2cd_3
  - pycparser=2.22=pyhd8ed1ab_0
  - pyparsing=3.1.2=pyhd8ed1ab_0
  - pysocks=1.7.1=pyh0701188_6
  - pysoundfile=0.12.1=pyhd8ed1ab_0
  - python=3.8.18=h4de0772_1_cpython
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python-tzdata=2024.1=pyhd8ed1ab_0
  - python_abi=3.8=4_cp38
  - pytz=2024.1=pyhd8ed1ab_0
  - requests=2.31.0=pyhd8ed1ab_0
  - scikit-learn=1.3.2=py38h4f736e5_2
  - scipy=1.10.1=py38h1aea9ed_3
  - setuptools=69.5.1=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - soxr=0.1.3=hcfcfb64_3
  - soxr-python=0.3.7=py38he7056a7_0
  - tbb=2021.12.0=h91493d7_0
  - threadpoolctl=3.4.0=pyhc1e730c_0
  - tk=8.6.13=h5226925_1
  - typing_extensions=4.11.0=pyha770c72_0
  - ucrt=10.0.22621.0=h57928b3_0
  - unicodedata2=15.1.0=py38h91455d4_0
  - urllib3=2.2.1=pyhd8ed1ab_0
  - vc=14.3=hcf57466_18
  - vc14_runtime=14.38.33130=h82b7239_18
  - vs2015_runtime=14.38.33130=hcb4865c_18
  - wheel=0.43.0=pyhd8ed1ab_1
  - win_inet_pton=1.1.0=pyhd8ed1ab_6
  - xorg-libxau=1.0.11=hcd874cb_0
  - xorg-libxdmcp=1.1.3=hcd874cb_0
  - xz=5.2.6=h8d14728_0
  - zipp=3.17.0=pyhd8ed1ab_0
  - zstd=1.5.5=h12be248_0
  - pip:
      - absl-py==2.1.0
      - astunparse==1.6.3
      - cachetools==5.3.3
      - flatbuffers==24.3.25
      - gast==0.4.0
      - google-auth==2.29.0
      - google-auth-oauthlib==1.0.0
      - google-pasta==0.2.0
      - grpcio==1.62.1
      - h5py==3.11.0
      - idna==3.7
      - keras==2.13.1
      - libclang==18.1.1
      - markdown==3.6
      - markupsafe==2.1.5
      - numpy==1.24.3
      - oauthlib==3.2.2
      - opt-einsum==3.3.0
      - protobuf==4.25.3
      - pyasn1==0.6.0
      - pyasn1-modules==0.4.0
      - pydub==0.25.1
      - pytube==15.0.0
      - requests-oauthlib==2.0.0
      - rsa==4.9
      - tensorboard==2.13.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.13.0
      - tensorflow-estimator==2.13.0
      - tensorflow-intel==2.13.0
      - tensorflow-io-gcs-filesystem==0.31.0
      - termcolor==2.4.0
      - typing-extensions==4.5.0
      - werkzeug==3.0.2
      - wrapt==1.16.0
prefix: C:\Users\denni\anaconda3\envs\chorus-detection
